emacs: updated scripts for building emacs

diff --git a/emacs/emacs/clean b/emacs/emacs/clean
--- a/emacs/emacs/clean
+++ b/emacs/emacs/clean
@@ -1,6 +1,15 @@
 #!/bin/bash
+EMACS_DIR=$(pwd)/emacs
+
+set -eEo pipefail
+trap 'printf "\n%s\n" "cleanup failed"' ERR
+
+mkdir -p build
+mv -f build build.old
+mkdir -p build
 
 (
-    cd emacs/ || exit 2
+    cd "$EMACS_DIR" || exit 2
     make clean distclean
+    echo "clean completed"
 )
diff --git a/emacs/emacs/install b/emacs/emacs/install
--- a/emacs/emacs/install
+++ b/emacs/emacs/install
@@ -1,9 +1,15 @@
 #!/bin/bash
+TARGET=build
 BUILD_DIR=$(pwd)/build
+INSTALL_DIR=$HOME/.local
+
+set -eEo pipefail
+trap 'printf "\n%s\n" "install failed for $TARGET to $INSTALL_DIR"' ERR
 
 # fix for stow not wanting to link into another symlink
-rm -r "$BUILD_DIR/man" &> /dev/null
-cp -r "$BUILD_DIR/share/man" "$BUILD_DIR/man"
+# rm -r "$BUILD_DIR/man" &> /dev/null
+# cp -r "$BUILD_DIR/share/man" "$BUILD_DIR/man"
 
-sudo stow --verbose --target ~/.local/ --stow build/
-echo "installation complete!"
+stow --verbose --target "$INSTALL_DIR" --stow "$TARGET"
+
+echo "installed emacs at $INSTALL_DIR"
diff --git a/emacs/emacs/setup b/emacs/emacs/setup
--- a/emacs/emacs/setup
+++ b/emacs/emacs/setup
@@ -1,6 +1,11 @@
 #!/bin/bash
+EMACS_DIR=$(pwd)/emacs
+
+set -eEo pipefail
+trap 'printf "\n%s\n" "setup failed"' ERR
 
 (
-    cd emacs/ || exit 2
-    ./autogen.sh
+    cd "$EMACS_DIR" || exit 2
+    ./autogen.sh all
+    echo "setup completed"
 )
diff --git a/emacs/emacs/uninstall b/emacs/emacs/uninstall
--- a/emacs/emacs/uninstall
+++ b/emacs/emacs/uninstall
@@ -1,4 +1,10 @@
 #!/bin/bash
 BUILD_DIR=$(pwd)/build
+INSTALL_DIR=$HOME/.local
 
-sudo stow --delete --target /usr/local "$BUILD_DIR"
+set -eEo pipefail
+trap 'printf "\n%s\n" "uninstall failed from $INSTALL_DIR"' ERR
+
+sudo stow --delete --target "$INSTALL_DIR" "$BUILD_DIR"
+
+echo "uninstalled emacs at $BUILD_DIR"
