updated lock-on-sleep and dim-on-wake systemd units; dimmer pass on the exitcode from redshift

diff --git a/root/usr/local/bin/dimmer b/root/usr/local/bin/dimmer
--- a/root/usr/local/bin/dimmer
+++ b/root/usr/local/bin/dimmer
@@ -97,5 +97,12 @@ fi
 if [ -n "$DIM" ]
 then
     redshift -P -O "$DIM" >> /dev/null
-    echo "dimmer: setting screen temp to $DIM"
+    rc=$?
+    if [ $rc -eq 0 ]; then
+        echo "dimmer: setting screen temp to $DIM"
+    else
+        echo "dimmer: failed to set screen temp"
+    fi
+
+    exit $rc
 fi
